aws:
  sealedCredentials: BACQFijFDG4V+aP1B2d9XAVApufCBSHNrnmbkcVgl+Tuyifj+A6YgFxn0kDFs3ZMEIxIWXzrlQORq4vIA+O2OYI/hmycxkHFxPAjDPuBJt1hcfqiKf+1YFJLkDjjsogdgvpEAQKt1TSQvi5oF8w4F4LJnW8J1A7qTStnGACufp4gWnD/ua6ChLP5dMXyWegIxbdFkxeU92UH7pwNygciLnuWcS3CGQzurONHV+T3hM3jT3jguf86lXAXAlgVNC7injn3JdRuwxwC5wwlPRzpQp9APiqjBQ8dz7bye1/6yUCwE8OY1M9z1VUt9sa/+oygGceRff/8gDfHAk0NgDqTgC9ZxolQnrpwl62dS8Rb/5IdHxT5uV1rSOe0iXM0qNjYsuAXOZJP9ipOxjSjSQPnWkKrLNrkvZQTx9JfGcrGWfgqq1fxDqIKt8bWImCq16OhdBs9E/fbvXfILcLIERBIVsfj4YAKOCZ4/zlEmTNwFMIIIdS52WH+sn6UMadlJoTvfU3OCuMe1I5FKCxbP0aAyYp5QxbCskWHBwOsQQnDhYHNhXaaObxrsLemj1Lfac/9Jl1NBYXpKJ+O83bWgpoTr3ShdGX23juekN4xl7aeweX/QuKhsUAvpP3Qvt+96TLIedTmEPKb6iE07R9XHH4uIN6i0ix3/41RdWtcE2hega34TkkEonaC+uU79eIJU80f9Z+xasdHh20CxCEyGj6vyhc5brpX5Zc+o0oQaKbUqgJ1KTH0TaxMznndql7S9F9QXYhzKgPpQgafgCpVb/jbcK1HzrYs/+X5wXaz7TCh1JoKyQMf/OYeDfpnab6sBCQPxIQfiQElBEjMM91rBVwCOyBibEASxNJbkyKieat9doil7kSy7YSKD0sm4kAtvoV3t3XCIdai5cUOR84BatgmTOZLafotVm0hzIlc+i7zkPK32t7LQaTUH9bMjwgH/1RlFY4Q9Vb/RJsIDVgCaVDOphlYzxH+bf+X9PTFIGKK54e3arNmWLspUvnEQhYNcyI+IQx6ZhqgbBu2NJlfxMi3vBroX4P/YPt+KVj5HHd1Ta9ByyoDQdQkJfr7IHz6bXprrqBIUqfl5hRav6lni/xQ50Io8EvfxiCv4B2QyDMAZS48IAOHFf0yUZTR0lhesEMMTOM0UVgMfuP8dPnQcWw1K5Bz/ujbV/nF+uCm+xs47/T5e/bYU2ijaO83ScsTusG3pjF2T+hj++2yZgTtrQ6ipzkUQ7At5cpfpAIDFjSB778mh75ZGeeN2ucQULzXrxVLW96mR/GhCuZ8+u1ZMa/iOsyh2B3zwmRI2pcQRhtYUTdtzYGMB5gickmUtpYoP0DnpkQPCBS5NCtc+lI43cbwKOiL7CxyfuGiRKVKSm99GUct1qaKf3duqe110CVegOD1HINgCZD/NzxtJWV4r5+FBGheET1HksWLQqCExqvQHDNCvo5NVkQ3IBSojFbmUGbYxgmgU4M4kjBcWEuA5GIBCyCb78HCDxuvgiPROgQIuGzt6OPr1UCEPeLR9TcucsxZ9/Hqt0S4
crossplane:
  resourcesCrossplane:
    limits: &localLimits
      cpu: 0m
    requests: &localRequests
      cpu: 0m
      memory: 0Mi
  resourcesRBACManager:
    limits: *localLimits
    requests: *localRequests
providers:
  awsS3:
    resources:
      limits: *localLimits
      requests: *localRequests
  default:
    resources:
      limits: *localLimits
      requests: *localRequests
