global:
  stage: local
aws:
  s3:
    roleARN: arn:aws:iam::737742117295:role/assume_s3_access
crossplane:
  resourcesCrossplane:
    requests:
      memory: 320Mi
providers:
  awsS3:
    image:
      registry: xpkg.upbound.io
      repository: upbound/provider-aws-s3
      tag: v2.1.1
    resources:
      limits:
        cpu: 250m
        memory: 320Mi
      requests:
        cpu: 50m
        memory: 160Mi
  default:
    resources:
      limits:
        cpu: 250m
        memory: 384Mi
      requests:
        cpu: 50m
        memory: 128Mi
