{{- if .Capabilities.APIVersions.Has "bitnami.com/v1alpha1/SealedSecret" -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws
spec:
  encryptedData:
    creds: {{ .Values.aws.sealedCredentials }}
{{- end -}}
