{{- if .Capabilities.APIVersions.Has "aws.upbound.io/v1beta1" }}
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-s3
spec:
  assumeRoleChain:
  - roleARN: "arn:aws:iam::737742117295:role/assume_s3_access"
  credentials:
    secretRef:
      key: creds
      name: aws
      namespace: crossplane-system
    source: Secret
{{ end }}
