{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1" }}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
spec:
  package: {{ .Values.providers.awsS3.image.registry }}/{{ .Values.providers.awsS3.image.repository }}:{{ .Values.providers.awsS3.image.tag }}
  runtimeConfigRef:
    name: aws-s3-provider
{{ end }}
