{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1beta1" }}
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            resources: {{ toYaml .Values.providers.default.resources | nindent 14 }}
{{ end }}
