{{- if .Capabilities.APIVersions.Has "pkg.crossplane.io/v1" }}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-minio
spec:
  package: {{ .Values.providers.minio.image.registry }}/{{ .Values.providers.minio.image.repository }}:{{ .Values.providers.minio.image.tag }}
  runtimeConfigRef:
    name: minio-provider
{{ end }}